import pdfFile from '../assets/pdfs/pdfPage.pdf';

export const forms = [
  {
    _id: '0',
    title: 'טופס חולים',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '1',
    title: 'טופס חו"ל',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '2',
    title: 'טופס טיולים',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '3',
    title: 'טופס חופשה',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '4',
    title: 'טופס נשק',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '5',
    title: 'פורמט ריאיון ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '6',
    title: 'טופס אימוץ קיפוד',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '7',
    title: 'הרשמה לקייטנה',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '8',
    title: 'ויתור ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '9',
    title: 'נוהל פנייה לשלישות',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '10',
    title: 'מש"ק ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '11',
    title: 'פנייה לשק"ם',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    files: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
];

export default forms;
