import pdfFile from '../assets/dummyMedia/pdfs/pdfPage.pdf';

export const forms = [
  {
    _id: '0',
    title: 'טופס חולים',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '1',
    title: 'טופס חו"ל',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '2',
    title: 'טופס טיולים',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '3',
    title: 'טופס חופשה',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '4',
    title: 'טופס נשק',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '5',
    title: 'פורמט ריאיון ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '6',
    title: 'טופס אימוץ קיפוד',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '7',
    title: 'הרשמה לקייטנה',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '8',
    title: 'ויתור ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '9',
    title: 'נוהל פנייה לשלישות',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: true }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '10',
    title: 'מש"ק ת"ש',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
  {
    _id: '11',
    title: 'פנייה לשק"ם',
    subject: { title: 'שלישות' },
    downloads: 500,
    settings: [{ isRecommended: false }],
    file: { media: { file: pdfFile, MimeType: 'pdf', fileName: 'מסמך' } },
    updatedAt: Date('28.8.2024'),
  },
];

export const formsSubjects = [
  {
    _id: '01',
    title: 'שלישות',
    forms: forms.slice(0, 3),
  },
  {
    _id: '02',
    title: 'ת"ש',
    forms: forms.slice(3, 5),
  },
  {
    _id: '03',
    title: 'יוהל"ם',
    forms: forms.slice(5, 6),
  },
  {
    _id: '04',
    title: 'חינוך',
    forms: forms.slice(6, 8),
  },
  {
    _id: '05',
    title: 'נפגעים',
    forms: [],
  },
  {
    _id: '06',
    title: 'בטיחות',
    forms: forms.slice(-3),
  },
];
