import party from '../assets/dummyMedia/party.png';
import rabit from '../assets/dummyMedia/rabit.jpg';
import robot from '../assets/dummyMedia/robot.jpg';
import usa from '../assets/dummyMedia/usa.png';

const media = [
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'סיום קורס מט"ל',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    updatedAt: '2021-08-01T12:00:00.000Z',
    files: [
      { media: { file: party, mimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, mimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, mimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, mimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, mimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, mimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, mimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'יום כיף בספארי',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    updatedAt: '2021-08-01T12:00:00.000Z',
    files: [
      { media: { file: party, mimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, mimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, mimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, mimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, mimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, mimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, mimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'פורימון 2021',
    pageType: 'תמונות סטוק',
    type: 'נושא',
    views: 500,
    updatedAt: '2021-08-01T12:00:00.000Z',
    files: [
      { media: { file: party, mimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, mimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, mimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, mimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, mimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, mimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, mimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'בה"ד 1',
    pageType: 'תמונות סטוק',
    type: 'נושא',
    views: 500,
    updatedAt: '2021-08-01T12:00:00.000Z',
    files: [
      { media: { file: party, mimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, mimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, mimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, mimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, mimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, mimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, mimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'סיום קורס קמ"נים',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    updatedAt: '2021-08-01T12:00:00.000Z',
    files: [
      { key: 1, fileName: 'ספורט', mimeType: 'image' },
      { key: 2, fileName: 'ספורט', mimeType: 'image' },
      { key: 3, fileName: 'ספורט', mimeType: 'image' },
    ],
  },
];

export default media;
