import party from '../assets/img/party.png';
import rabit from '../assets/img/rabit.jpg';
import robot from '../assets/img/robot.jpg';
import usa from '../assets/img/usa.png';

const media = [
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'סיום קורס מט"ל',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    files: [
      { media: { file: party, MimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, MimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, MimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, MimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, MimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, MimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'יום כיף בספארי',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    files: [
      { media: { file: party, MimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, MimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, MimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, MimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, MimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, MimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'פורימון 2021',
    pageType: 'תמונות סטוק',
    type: 'נושא',
    views: 500,
    files: [
      { media: { file: party, MimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, MimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, MimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, MimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, MimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, MimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'בה"ד 1',
    pageType: 'תמונות סטוק',
    type: 'נושא',
    views: 500,
    files: [
      { media: { file: party, MimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, MimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, MimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, MimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, MimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, MimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ארנב' } },
    ],
  },
  {
    _id: '66b46996cb231f6817ea15cb',
    title: 'סיום קורס קמ"נים',
    pageType: 'אלבום',
    type: 'נושא',
    views: 500,
    files: [
      { media: { file: party, MimeType: 'image', fileName: 'ספורט' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ים' } },
      { media: { file: robot, MimeType: 'image', fileName: 'רובוט' } },
      { media: { file: usa, MimeType: 'image', fileName: 'במבה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'פרחים' } },
      { media: { file: party, MimeType: 'image', fileName: 'פתח תקווה' } },
      { media: { file: party, MimeType: 'image', fileName: 'שלג' } },
      { media: { file: usa, MimeType: 'image', fileName: 'נמר' } },
      { media: { file: usa, MimeType: 'image', fileName: 'זברה' } },
      { media: { file: rabit, MimeType: 'image', fileName: 'ארנב' } },
    ],
  },
];

export default media;
